name: 'verify-manifest'
description: 'Verifies manifest.yml against missing submodule entires and stale version information'
inputs:
  manifest-path:
    description: 'Path to repository folder to run manifest verification verification on.'
    required: false
    default: ./
  exclude-submodules:
    description: 'Space separated list of git submodule paths to ignore.'
    required: false
    default: ''
  ignore-spdx:
    description: 'Space separated list of custom SPDX identifiers to be ignored.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Install python dependencies
      run: |
        sudo apt-get install -y python3-setuptools python3-pip
        python3 -m pip install -r $GITHUB_ACTION_PATH/requirements.txt
      shell: bash
    - name: Run manifest verifier script
      run: |
        if [ -n "${{ inputs.manifest_path }}" ]; then
          manifest_path=${{ inputs.manifest_path }}
          args+=${manifest_path:+ $manifest_path}
        fi
        if [ -n "${{ inputs.ignore_paths  }}" ]; then
          dirs=${{ inputs.ignore_paths }}
          args+=${dirs:+ --ignore-paths $dirs}
        fi
        if [ -n "${{ inputs.ignore_spdx  }}" ]; then
          ignore_spdx=${{ inputs.ignore_spdx }}
          args+=${ignore_spdx:+ --ignore-spdx $ignore_spdx}
        fi
        echo python3 $GITHUB_ACTION_PATH/verify_manifest.py $args
        python3 $GITHUB_ACTION_PATH/verify_manifest.py $args
        if [ $? -ne "0" ]
        then
          exit 1
        fi
      shell: bash
